apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: $(IMAGE_URI_BACKEND)
          ports:
            - containerPort: 8080
      env:
        - name: IMAGE_URI_BACKEND
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: IMAGE_URI_BACKEND
