apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bse256
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 654654367152.dkr.ecr.us-east-2.amazonaws.com/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: production
            - name: MONGO_URI
              value: mongodb://db:27017
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_DB
          readinessProbe:
            exec:
              command: ['node', 'healthcheck.js']
            initialDelaySeconds: 5
            periodSeconds: 30
