apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bse256
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 654654367152.dkr.ecr.us-east-2.amazonaws.com/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://root:root@mongodb:27017/db"
          readinessProbe:
            exec:
              command: ['node', 'healthcheck.js']
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
