name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test JavaScript API
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run frontend tests and collect coverage
        run: |
          cd frontend
          npm test -- --coverage --passWithNoTests

      - name: Run backend tests and collect coverage
        run: |
          cd backend
          npm test -- --coverage --passWithNoTests

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4.2.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
