name: CI/CD Pipeline

# Trigger the workflow on push or pull request to the staging branch
on:
  push:
    branches:
      - staging
    paths-ignore:
      - 'README.md'

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies and run tests for the backend
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run backend tests
        run: |
          cd backend/__tests__
          npm test -- --passWithNoTests

      # Install dependencies and run tests for the frontend
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend/__tests__
          npm test -- --passWithNoTests

  build-and-push-ecr-image:
    name: Continuous Delivery
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build and push backend Docker image
      - name: Build, tag, and push backend image to Amazon ECR
        id: build-backend-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_BACKEND_REPOSITORY_NAME }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      # Build and push frontend Docker image
      - name: Build, tag, and push frontend image to Amazon ECR
        id: build-frontend-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_FRONTEND_REPOSITORY_NAME }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

  deploy:
    runs-on: self-hosted
    needs: build-and-push-ecr-image
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Pull latest backend image
      #   run: |
      #     docker pull ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_BACKEND_REPOSITORY_NAME }}:latest

      # - name: Pull latest frontend image
      #   run: |
      #     docker pull ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_FRONTEND_REPOSITORY_NAME }}:latest

      # - name: Stop and remove existing backend container if running
      #   run: |
      #     docker ps -q --filter "name=backendapp" | grep -q . && docker stop backendapp && docker rm -fv backendapp

      # - name: Stop and remove existing frontend container if running
      #   run: |
      #     docker ps -q --filter "name=frontendapp" | grep -q . && docker stop frontendapp && docker rm -fv frontendapp

      # - name: Run Backend Docker Image
      #   run: |
      #     docker run -d -p 3000:3000 --name=backendapp -e 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' -e 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' -e 'AWS_REGION=${{ secrets.AWS_REGION }}' ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_BACKEND_REPOSITORY_NAME }}:latest

      # - name: Run Frontend Docker Image
      #   run: |
      #     docker run -d -p 80:80 --name=frontendapp ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_FRONTEND_REPOSITORY_NAME }}:latest

      # - name: Clean previous images and containers
      #   run: |
      #     docker system prune -f

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -k k8s/
