name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create budget.json if not exists
        run: |
          if [ ! -f ./budget.json ]; then
            echo '[{"path":"/*","timings":[{"metric":"interactive","budget":3000},{"metric":"first-contentful-paint","budget":1800}],"resourceSizes":[{"resourceType":"script","budget":125},{"resourceType":"total","budget":300}],"resourceCounts":[{"resourceType":"third-party","budget":10}]}]' > budget.json
          fi
        
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            http://3.13.201.22:3000/
          budgetPath: ./budget.json 
          uploadArtifacts: true 
          temporaryPublicStorage: true
