name: Security Scan

on:
  push:
    branches: [staging, production]
  pull_request:
    branches: [staging, production]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: List directory contents
        run: ls -R

      - name: Run Snyk on Backend
        working-directory: ./backend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npm install
          npx snyk test

      - name: Run Snyk on Frontend
        working-directory: ./frontend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npm install
          npx snyk test

      - name: Upload Snyk results
        uses: actions/upload-artifact@v2
        with:
          name: snyk-scan-results
          path: |
            ./backend/snyk-result.json
            ./frontend/snyk-result.json
        if: always()