name: Security Scan

on:
  push:
    branches: [staging, production]
  pull_request:
    branches: [staging, production]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: List directory contents
        run: ls -R
        
      - name: Check for package.json
        run: |
          if [ -f "./package.json" ]; then
            echo "package.json found"
            cat package.json
          else
            echo "package.json not found in the root directory"
            find . -name "package.json"
          fi

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --all-projects

      - name: Upload Snyk result
        uses: actions/upload-artifact@v2
        with:
          name: snyk-scan-result
          path: snyk-result.json
        if: always()